### ISSUE TITLE
Glen received 86 emails from an order

### ISSUE THREAD

**Issue by jacobpdq** [subsumo/envoy.website#27] opened 2015-07-22 14:29 UTC

**Comment by DrewMayne** [comment] 2015-07-23 01:05
Will need the order number or more info to diagnose this one

**Comment by DrewMayne** [comment] 2015-07-23 17:22
I believe this issue was caused by a bug fix for supplier order process missing from travelweekpro.ca.

Will need one more test from Glen before we can safely close this one out.

**Comment by gharwoodenvoy** [comment] 2015-07-23 17:43
Hi Andrew

It's working now ­ thanks!

The only issue is if I check off "rush order" it is being recorded in the
priority field as 0 instead of 1

Glen

From:  Andrew Mayne notifications@github.com
Reply-To:  "subsumo/envoy.website"
<reply+00cbb8fab69ad3786285708bf3869549b788e5b9710ec2fe92cf0000000111c8e4d79
2a169ce05c1b9df@reply.github.com>
Date:  Thu, 23 Jul 2015 10:22:31 -0700
To:  "subsumo/envoy.website" envoy.website@noreply.github.com
Cc:  Glen Harwood gharwood@envoynetworks.ca
Subject:  Re: [envoy.website] Glen received 86 emails from an order (#27)

I believe this issue was caused by a bug fix for supplier order process
missing from travelweekpro.ca.

Will need one more test from Glen before we can safely close this one out.



**Comment by DrewMayne** [comment] 2015-07-23 18:02
Will take another look at priority momentarily.

**Comment by DrewMayne** [comment] 2015-07-23 19:23
The view which should have accompanied this fix was not pushed along with the controller changes.

**Closed as completed by DrewMayne** 2015-07-23 19:23 UTC
